In [1]:
import numpy as np
import pandas as pd
import pickle
import copy
from sampling_method import random_sampling, population_annealing

In [2]:
with open('true_distribution_df_range21.pickle', 'rb') as p:
    true_distribution_df = pickle.load(p)

In [3]:
range_num = int(len(true_distribution_df)**(1/4))               #number of levels of each input parameters
rand_num = 20000                                                #number of sampling in each trials
trial_num = 5                                                   #number of trial

In [4]:
rs = random_sampling(true_distribution_df, range_num, rand_num)
random_sampling_df = rs.random_sample_from_df(trial_num)
random_sampling_df

,Conc,SM2_eq,Temp,Time,Total_failure,SM1_failure,SM2_failure,Iso_failure,Bis_failure,Yield,E_factor,Material_cost,STY,trial
8273,0.0,9.0,7.5,10.0,1.0,0.312,1.0,0.000,0.038,0.897677,620.700195,28686.609897,0.514020,0
106559,5.5,5.0,6.5,2.5,1.0,1.000,1.0,0.000,0.000,0.776723,46.178659,2174.391315,295.828388,0
93576,5.0,1.0,2.0,0.0,1.0,1.000,1.0,0.000,0.000,0.110315,423.679068,19536.048010,114.209462,0
123896,6.5,3.5,9.5,8.5,1.0,0.000,0.0,0.465,1.000,0.900035,24.118835,1157.873478,28.138249,0
52675,2.5,7.0,4.5,3.5,1.0,1.000,1.0,0.000,0.000,0.404501,396.287315,18320.164667,20.849950,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94288,5.0,1.5,8.0,9.5,1.0,0.000,0.0,0.276,1.000,0.902055,50.803399,2389.188945,8.079835,4
72691,3.5,8.5,8.5,5.0,1.0,1.000,1.0,0.000,0.000,0.877267,110.520800,5144.341937,35.216253,4
43836,2.0,7.5,4.0,4.5,1.0,1.000,1.0,0.000,0.000,0.414291,496.354057,22936.403622,10.087176,4
33329,1.5,6.0,6.0,1.0,1.0,1.000,1.0,0.000,0.000,0.177082,1491.434703,68826.791476,19.323291,4
135689,7.0,6.5,7.0,4.0,1.0,0.000,1.0,0.000,0.580,0.902131,18.778881,911.225964,343.592329,4

In [5]:
range_num = int(len(true_distribution_df)**(1/4))  #number of levels of each input parameters
walk_step = 2                                      #number of random walk step (+-)
bnum = 10                                          #number of levels of inverse temperature
betas = np.linspace(0.1,20,num=bnum)               #inverse tenmeratures
mcmc_num = 20                                      #number of mcmc steps of each particles in one temperature
num_population = 100                               #number of population
trial_num = 5                                      #number of trial

In [6]:
pa = population_annealing(true_distribution_df,range_num,num_population,mcmc_num,walk_step,betas)
EPA_sampling_df, _ = pa.pupolation_annealing_from_df(trial_num)
EPA_sampling_df

,Conc,SM2_eq,Temp,Time,Total_failure,SM1_failure,SM2_failure,Iso_failure,Bis_failure,Yield,E_factor,Material_cost,STY,beta,flag,trial
1362,0.0,1.5,0.5,9.0,1.000,1.000,1.0,0.000,0.000,0.292326,1909.540860,88087.606367,0.275978,0.1,1,0
19884,1.0,1.5,0.5,9.0,1.000,1.000,1.0,0.000,0.000,0.402462,841.603796,38851.204453,0.626440,0.1,1,0
29145,1.5,1.5,0.5,9.0,1.000,1.000,1.0,0.000,0.000,0.462428,570.542172,26355.292688,0.924213,0.1,1,0
28704,1.5,1.0,0.5,9.0,1.000,1.000,1.0,0.000,0.000,0.460394,573.059175,26471.600604,0.920148,0.1,1,0
28263,1.5,0.5,0.5,9.0,1.000,1.000,1.0,0.000,0.000,0.458913,574.904533,26556.877822,0.917188,0.1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167322,9.0,0.5,4.0,7.5,0.118,0.002,0.0,0.040,0.078,0.911889,6.884504,362.544891,164.057110,20.0,1,4
167280,9.0,0.5,3.0,7.5,0.025,0.004,0.0,0.019,0.006,0.913604,6.870166,361.864208,164.365709,20.0,1,4
167282,9.0,0.5,3.0,8.5,0.067,0.000,0.0,0.022,0.045,0.915273,6.855392,361.204600,99.874894,20.0,1,4
167282,9.0,0.5,3.0,8.5,0.067,0.000,0.0,0.022,0.045,0.915273,6.855392,361.204600,99.874894,20.0,0,4
148760,8.0,0.5,3.0,8.5,0.024,0.005,0.0,0.016,0.008,0.913799,11.261777,564.509758,60.479666,20.0,1,4

In [7]:
with open("random_sampling_range21.pickle", mode="wb") as f:
    pickle.dump(random_sampling_df, f)
with open("EPA_sampling_range21.pickle", mode="wb") as f:
    pickle.dump(EPA_sampling_df, f)